services:
  - type: web
    name: telegram-report-bot
    runtime: python
    pythonVersion: 3.12.10
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false  
      - key: CHANNEL_ID
        sync: false
      - key: WEBHOOK_SECRET
        sync: false